// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenantSaaS.Infrastructure.Persistence;

#nullable disable

namespace MultiTenantSaaS.Infrastructure.Persistence.Migrations.Performance
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20261004142153_InitialPerformance")]
    partial class InitialPerformance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiTenantSaaS.Domain.Entities.Performance.TracksheetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("AvgF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AvgSpeedO")
                        .HasColumnType("float");

                    b.Property<double?>("Course")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CurrF")
                        .HasColumnType("float");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DistO")
                        .HasColumnType("float");

                    b.Property<double?>("DistR")
                        .HasColumnType("float");

                    b.Property<double?>("DtgO")
                        .HasColumnType("float");

                    b.Property<double?>("EnginePower")
                        .HasColumnType("float");

                    b.Property<double?>("Hrs")
                        .HasColumnType("float");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LsmgoBunkered")
                        .HasColumnType("float");

                    b.Property<double?>("LsmgoCorrected")
                        .HasColumnType("float");

                    b.Property<double?>("LsmgoRob")
                        .HasColumnType("float");

                    b.Property<string>("NextPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NoneBunkered")
                        .HasColumnType("float");

                    b.Property<double?>("NoneCorrected")
                        .HasColumnType("float");

                    b.Property<double?>("NoneRob")
                        .HasColumnType("float");

                    b.Property<double?>("Rpm")
                        .HasColumnType("float");

                    b.Property<string>("Rt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Slip")
                        .HasColumnType("float");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VesselImo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("VlsfoBunkered")
                        .HasColumnType("float");

                    b.Property<double?>("VlsfoCorrected")
                        .HasColumnType("float");

                    b.Property<double?>("VlsfoRob")
                        .HasColumnType("float");

                    b.Property<string>("VoyageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("WaveF")
                        .HasColumnType("float");

                    b.Property<string>("WavesO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WindF")
                        .HasColumnType("float");

                    b.Property<string>("WindO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "VoyageId", "SortOrder");

                    b.ToTable("TracksheetRows", (string)null);
                });

            modelBuilder.Entity("MultiTenantSaaS.Domain.Entities.Performance.VoyagePerformanceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VesselImo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VoyageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "VoyageId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("VoyagePerformanceReports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
