 - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'odasbackend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
